#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v4
# autospec commit: 1ab68caa3dd3
#
Name     : UxPlay
Version  : 1.68.2
Release  : 1
URL      : https://github.com/FDH2/UxPlay/archive/v1.68.2/UxPlay-1.68.2.tar.gz
Source0  : https://github.com/FDH2/UxPlay/archive/v1.68.2/UxPlay-1.68.2.tar.gz
Summary  : AirPlay-Mirror and AirPlay-Audio server
Group    : Development/Tools
License  : GPL-3.0 GPL-3.0+ MIT
Requires: UxPlay-bin = %{version}-%{release}
Requires: UxPlay-license = %{version}-%{release}
Requires: UxPlay-man = %{version}-%{release}
BuildRequires : avahi-dev
BuildRequires : buildreq-cmake
BuildRequires : gst-plugins-base-dev
BuildRequires : openssl-dev
BuildRequires : pkg-config
BuildRequires : pkgconfig(gstreamer-1.0)
BuildRequires : pkgconfig(libplist-2.0)
BuildRequires : pkgconfig(x11)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
An AirPlay2 Mirror and AirPlay2 Audio (but not Video) server that provides
screen-mirroring (with audio) of iOS/MacOS clients in a display window on
the server host (which can be shared using a screen-sharing application);
Apple Lossless Audio (ALAC) (e.g.,iTunes) can be streamed from client to
server in non-mirror mode

%package bin
Summary: bin components for the UxPlay package.
Group: Binaries
Requires: UxPlay-license = %{version}-%{release}

%description bin
bin components for the UxPlay package.


%package doc
Summary: doc components for the UxPlay package.
Group: Documentation
Requires: UxPlay-man = %{version}-%{release}

%description doc
doc components for the UxPlay package.


%package license
Summary: license components for the UxPlay package.
Group: Default

%description license
license components for the UxPlay package.


%package man
Summary: man components for the UxPlay package.
Group: Default

%description man
man components for the UxPlay package.


%prep
%setup -q -n UxPlay-1.68.2
cd %{_builddir}/UxPlay-1.68.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1709923692
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake .. -DNO_MARCH_NATIVE=ON
make  %{?_smp_mflags}
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1709923692
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/UxPlay
cp %{_builddir}/UxPlay-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/UxPlay/31a3d460bb3c7d98845187c716a30db81c44b615 || :
cp %{_builddir}/UxPlay-%{version}/lib/llhttp/LICENSE-MIT %{buildroot}/usr/share/package-licenses/UxPlay/f7eb77642fea2d18bc5b53d361802ca0fb698b3e || :
cp %{_builddir}/UxPlay-%{version}/lib/playfair/LICENSE.md %{buildroot}/usr/share/package-licenses/UxPlay/f5569602a1418fa6825691143b7beedb3ac9bf1e || :
export GOAMD64=v2
GOAMD64=v2
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/uxplay

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/uxplay/LICENSE
/usr/share/doc/uxplay/README.html
/usr/share/doc/uxplay/README.md
/usr/share/doc/uxplay/README.txt
/usr/share/doc/uxplay/llhttp/LICENSE-MIT

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/UxPlay/31a3d460bb3c7d98845187c716a30db81c44b615
/usr/share/package-licenses/UxPlay/f5569602a1418fa6825691143b7beedb3ac9bf1e
/usr/share/package-licenses/UxPlay/f7eb77642fea2d18bc5b53d361802ca0fb698b3e

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/uxplay.1
